### ISSUE TITLE
[1.5 pt] Research about Frontend - Backend Communication

### ISSUE THREAD

**Issue by eapenzacharias** [Maha-Magdy/pick-a-doctor#2]
## Research about Frontend - Backend communication

- [x] Research about the benefit of separating frontend and backend  and keeping it together
- [x] Finalize project structure

**Comment by Maha-Magdy** [comment]
After research, I have found that when they become two apps, one for BE and another for Fe, the maintenance of the project is easy. Because when they are in one app, and there is a problem in React framework, it takes a lot to solve it and to know where we have to suppose put a specific configuration. Besides, the community support when the question regarding one stack is better than if two are together in one app.
